### ISSUE TITLE
[申請人工文章判定] [資訊量不足] Discussion from Lin110303011

### ISSUE THREAD

**Issue by VictorLin2002** [1101-GS3073-C/Python-Community-GS3073-C#667]
原文被AI評價為「資訊量不足」
原文網址：https://github.com/NCU-GS3073-AI-Introduction/ai-introduction-community/discussions/666
原文內容：
在今年美國CES展中，科技公司Opteev Technologies展出運用AI技術開發的一款口袋大病毒檢測器ViraWarn，只要對儀器吹氣兩次，便可在60秒內檢測出COVID-19、RSV和流感，且可重複使用，這個儀器目前已經在等待美國FDA審核。其利用抓取病毒表面的電荷數據，並以AI分析，濾除錯誤讀數，即可知呼吸道是否被病毒感染。該公司希望藉此提供更方

說明：

**Comment by chia-kai-chang** [comment]
因為這是一篇Discussion，點數是3點，所以對於文章的資訊量要求較高。

建議可以閱讀同主題的相關文章，將資料用自己的話彙整後以文字說明，將會提高資訊量。

如果還是被評價為資訊量不足，歡迎再次開啟Issue。
