### ISSUE TITLE
[申請人工文章判定]%20[資訊量不足]%20Discussion%20from%20HsuChen88

### ISSUE THREAD

**Issue by HsuChen88** [1101-GS3073-C/Python-Community-GS3073-C#729]
原文被AI評價為「資訊量不足」%0A原文網址：https://github.com/NCU-GS3073-AI-Introduction/ai-introduction-community/discussions/728%0A原文內容：%0A%23%20什麼是GUI?%0D%0A圖形使用者介面（Graphical%20User%20Interface），圖形使用者介面是一種人與計算機通訊的介面顯示格式，允許使用者使用滑鼠等輸入裝置操縱螢幕上的圖示或選單選項，以選擇命令、呼叫檔案、啟動程式或執行其它一些日常任務。%0D%0A%0D%0A現今市面上不缺面向Python的GUI框架。**Tkinter**、**WxPython**、**Qt%0A%0A說明：%0A

**Comment by chia-kai-chang** [comment]
已撤銷AI判斷 😄 ，並加贈4點 👍 🎉 ，加上原文3點，總共7點
